if(WIN32)
    set(vulkan_lib ${EXTERN_LIB_DIR}/VulkanSDK/lib/Win32/vulkan-1.lib)
    set(glslangValidator_executable ${EXTERN_LIB_DIR}/VulkanSDK/bin/Win32/glslangValidator.exe)
    add_compile_definitions("NEO_VK_LAYER_PATH=${EXTERN_LIB_DIR}/VulkanSDK/bin/Win32")
elseif(UNIX)
    if(APPLE)
      set(vulkan_lib ${EXTERN_LIB_DIR}/VulkanSDK/lib/MacOS/libvulkan.1.dylib)
      set(glslangValidator_executable ${EXTERN_LIB_DIR}/VulkanSDK/bin/MacOS/glslangValidator)
      add_compile_definitions("NEO_VK_LAYER_PATH=${EXTERN_LIB_DIR}/VulkanSDK/bin/MacOS")
      add_compile_definitions("NEO_VK_ICD_FILENAMES=${EXTERN_LIB_DIR}/VulkanSDK/bin/MacOS/MoltenVK_icd.json")
    else()
      set(vulkan_lib ${EXTERN_LIB_DIR}/VulkanSDK/lib/Linux/libvulkan.so.1)
      set(glslangValidator_executable ${EXTERN_LIB_DIR}/VulkanSDK/bin/Linux/glslangValidator)
      add_compile_definitions("NEO_VK_LAYER_PATH=${EXTERN_LIB_DIR}/VulkanSDK/bin/Linux")
    endif()
else()
  message(FATAL_ERROR "Unknown Platform")
endif()